<?php

namespace ContainerOl06e43;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_93gWzSRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.93gWzSR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.93gWzSR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\AccountController::list' => ['privates', '.service_locator.P.blNFL.App\\Controller\\AccountController::list()', 'getAccountControllerlistService', true],
            'App\\Controller\\AccountController::create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\AccountController::create()', 'getAccountControllercreateService', true],
            'App\\Controller\\AccountController::delete' => ['privates', '.service_locator.P.blNFL.App\\Controller\\AccountController::delete()', 'getAccountControllerdeleteService', true],
            'App\\Controller\\ClientController::list' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ClientController::list()', 'getClientControllerlistService', true],
            'App\\Controller\\ClientController::create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ClientController::create()', 'getClientControllercreateService', true],
            'App\\Controller\\ClientController::delete' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ClientController::delete()', 'getClientControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\AccountController:list' => ['privates', '.service_locator.P.blNFL.App\\Controller\\AccountController::list()', 'getAccountControllerlistService', true],
            'App\\Controller\\AccountController:create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\AccountController::create()', 'getAccountControllercreateService', true],
            'App\\Controller\\AccountController:delete' => ['privates', '.service_locator.P.blNFL.App\\Controller\\AccountController::delete()', 'getAccountControllerdeleteService', true],
            'App\\Controller\\ClientController:list' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ClientController::list()', 'getClientControllerlistService', true],
            'App\\Controller\\ClientController:create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ClientController::create()', 'getClientControllercreateService', true],
            'App\\Controller\\ClientController:delete' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ClientController::delete()', 'getClientControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AccountController::list' => '?',
            'App\\Controller\\AccountController::create' => '?',
            'App\\Controller\\AccountController::delete' => '?',
            'App\\Controller\\ClientController::list' => '?',
            'App\\Controller\\ClientController::create' => '?',
            'App\\Controller\\ClientController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AccountController:list' => '?',
            'App\\Controller\\AccountController:create' => '?',
            'App\\Controller\\AccountController:delete' => '?',
            'App\\Controller\\ClientController:list' => '?',
            'App\\Controller\\ClientController:create' => '?',
            'App\\Controller\\ClientController:delete' => '?',
        ]);
    }
}
