<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLFV7lXT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLFV7lXT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLFV7lXT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLFV7lXT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLFV7lXT\App_KernelDevDebugContainer([
    'container.build_hash' => 'LFV7lXT',
    'container.build_id' => '050254b2',
    'container.build_time' => 1730133014,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLFV7lXT');
