<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0JWq5oA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0JWq5oA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0JWq5oA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0JWq5oA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0JWq5oA\App_KernelDevDebugContainer([
    'container.build_hash' => '0JWq5oA',
    'container.build_id' => '6392ce7e',
    'container.build_time' => 1729800139,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0JWq5oA');
